name: Build and Deploy

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -U git+https://github.com/EsauM10/cron_viewer.git

      - name: Generate Cron Docs
        run: cronv deploy --output=crons --env_file=".env"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: crons/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
